BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[ExploracionFisica] ALTER COLUMN [movAnormales] NVARCHAR(1000) NOT NULL;
ALTER TABLE [dbo].[ExploracionFisica] ALTER COLUMN [marcha] NVARCHAR(1000) NOT NULL;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
